version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    depends_on:
      - my-app
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - awesome
  my-app:
    build:
      context: .
    # Проброс порта так же, как в командной строке — на какой порт хоста какой порт контейнера
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    # Проброс файлов, откуда с хоста, куда в контейнер
    restart: always
    env_file: .env
    networks:
      - awesome

  postgres:
    container_name: custom_name # Можно и не указывать, тогда будет взято за основу название сервиса: `postgres`
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    env_file: .env
    networks:
      - awesome

volumes:
  pgadmin-data:

networks:
  awesome:
    driver: bridge