export const consts = {
    gamesTitle: 'CRAZY BOMBER',
    linkBack: '<<',
    loginPage: {
        login: 'Login',
        password: 'password',
        buttonOK: 'OK!',
        buttonSignUp: 'sign up',
    },
    signinPage: {
        email: 'email',
        login: 'Login',
        name: 'Name',
        password: 'Password',
        passwordRepeat: 'Password',
        buttonBack: '<<',
        buttonSignIn: 'sign in',
    },
    error: {
        errorIsEmpty: 'fill in the field',
        errorEmail: 'email invalid',
        errorPasswordRepeat: 'password mismatch',
        errorMinLength: 'enter more than 3 characters',
        errorMaxLength: 'enter less than 16 characters',
    },
    leaderBoardPage: {
        pageTitle: 'Leaderboard',
        loginHeader: 'Login',
        scoreHeader: 'Score',
    },
    profilePage: {
        pageTitle: 'Profile',
        email: 'email',
        login: 'Login',
        name: 'Name',
        oldPassword: 'Old password',
        newPassword: 'New password',
        buttonSaveChanges: 'Save changes',
    },
    startPage: {
        buttonPlay: 'Play!',
    },
    forumPage: {
        pageTitle: 'Forum',
        buttonCreateTopic: 'Create new topic',
        buttonPrevious: 'previous',
        buttonNext: 'next',
        messageInput: 'Your message: ',
    },
    navigation: {
        navLinkStart: 'start',
        navLinkProfile: 'profile',
        navLinkLeaderboard: 'leaderboard',
        navLinkForum: 'forum',
        navLinkPlayAgain: 'play again',
        navLinkLogin: 'login',
        navLinkLogout: 'logout',
    },
    errorBoundary: {
        title: '500',
        text: 'Something went wrong',
    },
    gameover: {
        title: 'GAME OVER',
        scoreText: 'Score: ',
        buttonPlayAgain: 'Play again!',
    },
};
